### ISSUE TITLE
Fulfillment response says there are no availablie times when the calendar is open

### ISSUE THREAD

**Issue by kdmyers56** [priyankavergadia/AppointmentScheduler#10]
Hello,
the installation went well.  Everything appears to be working.  However, I always get the following response no matter what day/time I ask for a call.  I am requesting times that I know are open.  

"{
  "fulfillmentText": "I'm sorry, there are no times available for March 7, 3 PM.",
  "outputContexts": []
}"

Raw API Response:
{
  "responseId": "12941c25-6571-4a16-90ef-d61694369554-19db3199",
  "queryResult": {
    "queryText": "My Name is Kelly. Please schdule an appointment for 430 PM today. My phone number is 505-270-5990",
    "parameters": {
      "given-name": "name",
      "time": "2020-03-07T16:30:00-05:00",
      "date-period": "",
      "date": "2020-03-07T12:00:00-05:00",
      "phone-number": "phone"
    },
    "allRequiredParamsPresent": true,
    "fulfillmentText": "I'm sorry, there are no times available for March 7, 3 PM.",
    "fulfillmentMessages": [
      {
        "text": {
          "text": [
            "I'm sorry, there are no times available for March 7, 3 PM."
          ]
        }
      }
    ],
    "intent": {
      "name": "projects/appointmentscheduler-dudrfn/agent/intents/ae76ebb0-3ee7-46f3-ac7e-c8291a2045b1",
      "displayName": "Schedule Appointment"
    },
    "intentDetectionConfidence": 0.56380177,
    "diagnosticInfo": {
      "webhook_latency_ms": 470
    },
    "languageCode": "en"
  },
  "webhookStatus": {
    "message": "Webhook execution successful"
  }
}

Fulfillment Request: 
{
  "responseId": "12941c25-6571-4a16-90ef-d61694369554-19db3199",
  "queryResult": {
    "queryText": "My Name is Kelly. Please schdule an appointment for 430 PM today. My phone number is 505-270-5990",
    "parameters": {
      "date": "2020-03-07T12:00:00-05:00",
      "time": "2020-03-07T16:30:00-05:00",
      "phone-number": "phone",
      "given-name": "name",
      "date-period": ""
    },
    "allRequiredParamsPresent": true,
    "fulfillmentText": "We look forward to our call on 2020-03-07   We will ask for name at phone",
    "fulfillmentMessages": [
      {
        "text": {
          "text": [
            "We look forward to our call on 2020-03-07   We will ask for name at phone"
          ]
        }
      }
    ],
    "outputContexts": [
      {
        "name": "projects/appointmentscheduler-dudrfn/agent/sessions/18a8ecf1-d9d7-fa96-80e0-6921d887ad60/contexts/__system_counters__",
        "parameters": {
          "no-input": 0,
          "no-match": 0,
          "date": "2020-03-07T12:00:00-05:00",
          "date.original": "today",
          "time": "2020-03-07T16:30:00-05:00",
          "time.original": "430 PM",
          "phone-number": "phone",
          "phone-number.original": "phone",
          "given-name": "name",
          "given-name.original": "Name",
          "date-period": "",
          "date-period.original": ""
        }
      }
    ],
    "intent": {
      "name": "projects/appointmentscheduler-dudrfn/agent/intents/ae76ebb0-3ee7-46f3-ac7e-c8291a2045b1",
      "displayName": "Schedule Appointment"
    },
    "intentDetectionConfidence": 0.56380177,
    "languageCode": "en"
  },
  "originalDetectIntentRequest": {
    "payload": {}
  },
  "session": "projects/appointmentscheduler-dudrfn/agent/sessions/18a8ecf1-d9d7-fa96-80e0-6921d887ad60"

**Comment by vikivyas** [comment]
Dear review below patch.
https://github.com/vikivyas/AppointmentScheduler-GoogleCalendar/blob/patch-1/index.js

**Comment by priyankavergadia** [comment]
Thanks for the patch!
