### ISSUE TITLE
Appointments are not shown in Calendar

### ISSUE THREAD

**Issue by Candlegreen** [priyankavergadia/AppointmentScheduler#12]
Goodday,

Thank you for the clear instruction videos, it was interesting to learn the steps in making an appointment agent. However, after deploying your code I don't see the scheduled appointments in my Calendar. I went through the steps twice and I don't get any error.

Could you please help me out?

**Comment by priyankavergadia** [comment]
You need to make sure the service account is accurate. If your service account is not correct the calendar invite will not be created.
