### ISSUE TITLE
on calendar descriptions says "undefined Appointment"

### ISSUE THREAD

**Issue by Smarto-Dev** [priyankavergadia/AppointmentScheduler#3]
When I book an appointment it gets marked on the calendar but says "undefined Appointment"

**Comment by Smarto-Dev** [comment]
@priyankavergadia

**Comment by priyankavergadia** [comment]
Make sire this line has the values defined for the calendar invite to show the name and description of the appointment. 
 resource: {summary: appointment_type +' Appointment', description: appointment_type,

**Comment by Smarto-Dev** [comment]
thank you so much
