### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by marcozammarchi** [priyankavergadia/AppointmentScheduler#5]
Hi Priyanka
how are you
every time I try to test the bot it says:
I'm sorry, there are no slots available for Invalid Date.

**Comment by vikivyas** [comment]
marcozammarchi : may be your time zone is +gmt and in code only work with -gmt

All issues are corved and patched here.

https://github.com/vikivyas/AppointmentScheduler-GoogleCalendar/blob/patch-1/index.js

**Comment by priyankavergadia** [comment]
Thaks Viki!!
