### ISSUE TITLE
Not get marked on the calendar

### ISSUE THREAD

**Issue by uaway** [priyankavergadia/AppointmentScheduler#7]
Hi, Priyanka (@priyankavergadia).

When I book an appointment it not get marked on the calendar. Dialogflow is working fine and it not show any errors. In the logs wrote: 

dialogflowFirebaseFulfillment
Warning, estimating Firebase Config based on GCLOUD_PROJECT. Intializing firebase-admin may fail
5:40:55.727 PM
dialogflowFirebaseFulfillment
Parameters { time: [ '2019-11-16T00:00:00+02:00' ], date: [ '2019-11-16T12:00:00+02:00' ], process: [ 'test' ], name: [ 'test' ], phone: [ '59678889900' ] }
5:40:55.729 PM
dialogflowFirebaseFulfillment
TypeError: agent.parameters.date.split is not a function at makeAppointment (/srv/index.js:58:70) at WebhookClient.handleRequest (/srv/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:303:44) at exports.dialogflowFirebaseFulfillment.functions.https.onRequest (/srv/index.js:75:10) at cloudFunction (/srv/node_modules/firebase-functions/lib/providers/https.js:57:9) at /worker/worker.js:783:7 at /worker/worker.js:766:11 at _combinedTickCallback (internal/process/next_tick.js:132:7) at process._tickDomainCallback (internal/process/next_tick.js:219:9)
5:40:55.735 PM
dialogflowFirebaseFulfillment
Function execution took 579 ms, finished with status: 'crash'

**Comment by vikivyas** [comment]
you are on +gmt timezone.

kindly go to below link and then you may close this issue.

https://github.com/vikivyas/AppointmentScheduler-GoogleCalendar/blob/patch-1/index.js
